apiVersion: v1
kind: ConfigMap
metadata:
  name: app-properties
data:
  appUrl: "http://my-app-service"
  timeout: "30"

---

apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:  
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
        name: app-properties
    command: ["/bin/bash"]
    #args: ["-c", "env && sleep 3600"]  # /bin/bash -c "env && sleep 3600"
    args: ["-c","echo $appUrl && sleep 3600"]

# kubectl apply -f 04-inject-cm-as-env-nginx.yaml
# kubectl logs my-pod ( we can see the env all variables)

