apiVersion: v1
kind: ConfigMap
metadata:
  name: app-properties
data:
  application.properties: |
    appUrl=http://my-app-service
    timeout=30
    a.b.c.d=something
    username=prashant    

---

apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers: 
   - name: ubuntu
     image: ubuntu
     command: ["sleep","3600"]
     

