apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  username: cm9vdA==
  password: YWRtaW5AMTIz

# echo -n 'root' | base64        # Outputs: cm9vdA==
# echo -n 'admin@123' | base64   # Outputs: YWRtaW5AMTIz
