apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
data:
  username: cm9vdA==
  password: YWRtaW5AMTIz

# echo -n 'root' | base64        # Outputs: cm9vdA==
# echo -n 'admin@123' | base64   # Outputs: YWRtaW5AMTIz

---

apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    env:
    - name: "app_username"
      valueFrom:
        secretKeyRef:
          name: my-app-secret
          key: username
    - name: "app_password"
      valueFrom:
        secretKeyRef:
          name: my-app-secret
          key: password
    args:
    - env            


# => kubectl apply -f 08-inject-simple-secret.yaml

# => kubectl logs my-pod
# PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
# HOSTNAME=my-pod
# app_username=root
# app_password=admin@123
# HOME=/root

