apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  username: cm9vdA==
  password: YWRtaW5AMTIz

# echo -n 'root' | base64        # Outputs: cm9vdA==
# echo -n 'admin@123' | base64   # Outputs: YWRtaW5AMTIz

---

apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    envFrom:
    - secretRef:
        name: app-secret
    args:
    - env    

# commands 

# => kubectl apply -f 07-simple-secret.yaml
# => kubectl logs my-pod
# PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
# HOSTNAME=my-pod 
# password=admin@123
# username=root
# KUBERNETES_SERVICE_PORT_HTTPS=443
# KUBERNETES_PORT=tcp://10.96.0.1:443
# KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
# KUBERNETES_PORT_443_TCP_PROTO=tcp
# KUBERNETES_PORT_443_TCP_PORT=443
# KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
# KUBERNETES_SERVICE_HOST=10.96.0.1
# KUBERNETES_SERVICE_PORT=443
# HOME=/root


