apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  custom.properties: |
    YXBwVXJsPSJodHRwOi8vbG9jYWxob3N0OjgwODAiCnRpbWVvdXQ9IjMwIgo=
    
# Decodes to:
# appUrl="http://localhost:8080"
# timeout="30"

---

apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  terminationGracePeriodSeconds: 0
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    volumeMounts:
    - name: secret-volume
      mountPath: /usr/share/props  
    args:
    - sleep
    - "3600"
  volumes:
  - name: secret-volume
    secret:
      secretName: app-secret

#  /usr/share/props/custom.properties:      
#  appUrl="http://localhost:8080"
#  timeout="30"

# => kubectl exec -it my-pod -- /bin/sh
# cat /usr/share/props/custom.properties