apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  app.properties: |
    YXBwLm5hbWU9TXlBcHAKYXBwLnBvcnQ9ODA4MAp0aW1lb3V0PTMwCnVzZXI9cHJhc2hhbnQK
    
# echo "app.name=MyApp\napp.port=8080\nuser=prashant\ntimeout=30" | base64
# This base64 content decodes to:
# app.name=MyApp
# app.port=8080
# timeout=30
# user=prashant    

---

apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
        - echo "Reading secret from custom path:"; 
          cat /custom/config/props/app.properties; 
          sleep 3600
    volumeMounts:
    - name: secret-vol
      mountPath: etc/custom/config/props
      readOnly: true
  volumes:
  - name: secret-vol
    secret:
      secretName: app-secret

# => kubectl apply -f 10-inject-secret-file.yaml
# => kubectl logs app-pod      