apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: service-1
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  # Maps to containerPort 80 in nginx

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-echo
  template:
    metadata:
      labels:
        app: http-echo
    spec:
      containers:
        - name: http-echo
          image: hashicorp/http-echo # HTTP server that simply returns a static message
          args:
            - "-text=Hello from HTTP Echo"
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: service-2
spec:
  selector:
    app: http-echo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  # Maps to containerPort 80 in http-echo



# docker run hashicorp/http-echo -text="Hello A"
# hashicorp/http-echo is a minimal HTTP server that simply returns a static message.
# -text="Hello A" specifies the text to be returned as the response to any HTTP request.
# containerPort: 80 exposes port 80 inside the container to handle incoming HTTP traffic.

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-ingress
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /nginx
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
          - path: /echo
            pathType: Prefix
            backend:
              service:
                name: http-echo-service
                port:
                  number: 80

# Ingress: The ingress maps two paths (/nginx and /echo) to the respective services (nginx-service and http-echo-service).
# Request http://example.com/nginx will go to the Nginx service.
# Request http://example.com/echo will go to the HTTP Echo service.                  