apiVersion: v1
kind: Pod
metadata:
  name: liveness-demo
  labels:
    app: liveness-demo
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /wrong-path   # ❌ Invalid path
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 1
        failureThreshold: 3

---

apiVersion: v1
kind: Service
metadata:
  name: liveness-demo-svc
spec:
  selector:
    app: liveness-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

# commands 
# watch -t 'kubectl get pods && echo && kubectl get svc && echo && kubectl describe pod liveness-demo && echo && kubectl describe svc liveness-demo-svc'
# => kubectl apply -f 06-probe-svc.yaml

# NAME            READY   STATUS    RESTARTS      AGE
# liveness-demo   1/1     Running   3 (30s ago)   2m  # keep restarting which makes pod  ready
# Liveness probe failed: HTTP probe failed with statuscode: 404
# Liveness Probe: Checks if the container is alive. If it fails, Kubernetes restarts the container.

# Field	Meaning
# READY 1/1	Pod is ready (no readiness probe or it passed if defined)
# STATUS Running	Pod is running (restarted container but now up again)
# RESTARTS 3	Container has restarted 3 times due to failed liveness
# AGE 2m	Pod was created 2 minutes ago
# Liveness probe failed: HTTP probe failed with statuscode: 404	Probe tried to hit /wrong-path and got 404 instead of 200


#Name:                     liveness-demo-svc
# Namespace:                default
# Labels:                   <none>
# Annotations:              <none>
# Selector:                 app=liveness-demo
# Type:                     ClusterIP
# IP Family Policy:         SingleStack
# IP Families:              IPv4
# IP:                       10.96.58.61
# IPs:                      10.96.58.61
# Port:                     <unset>  80/TCP
# TargetPort:               80/TCP
# Endpoints:                10.244.1.7:80  # see the pod IP , still there 
# Session Affinity:         None
# Internal Traffic Policy:  Cluster
# Events:                   <none>
prashant@Prashants-MacBook-Pro part06-probe % 