apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

# Command to apply the deployment
# => kubectl apply -f part05-service/01-simple-deploy.yaml
# Command to check the deployment
# => kubectl get deploy
# => Command to check the pods
# => kubectl get pods
# Command to check the logs of the pod        
# => kubectl logs <pod-name>
# Command to check the events of the pod
# => kubectl describe pod <pod-name>
# Command to check the events of the deployment
# => kubectl describe deploy <deploy-name>
# Command to delete the deployment
# => kubectl delete deploy <deploy-name>
# Command to delete the pod
# => kubectl delete pod <pod-name>
# Command to delete all the resources in the namespace
# => kubectl delete all --all -n <namespace>