apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 3
  template:
    metadata:
      labels:
        app: my-app
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: nginx
        image: vinsdocker/nginx-gke # this container will gives the pod name
        ports:
        - containerPort: 80

---
# Port Range: 30000–32767.
# Exposes the service on a static port on each node.
apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
  - port: 80 # port is the port that the service will be exposed on
    targetPort: 80
    nodePort: 30001 # will be used from the external world
       

# commands

# => kubectl apply -f 06-nord-port.yaml       
# => http://localhost:8080
