apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
     dept: dev
     team: development-1
spec:
  containers:
    - name: my-container1
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
  labels:
     dept: dev
     team: development-2
spec:
  containers:
    - name: my-container2
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod3
  labels:
     dept: test
     team: testing-1
spec:
  containers:
    - name: my-container3
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod4
  labels:
     dept: test
     team: testing-2
spec: 
  containers:
    - name: my-container4
      image: nginx      

# Create the pods with dept dev which has  team development-1 and development-2
# Create the pods with dept test which has team testing-1 and testing-2

# create the pods
# => kubectl create -f part02-pods/03-multiple-pods.yaml

# => kubectl describe pod (will describe all the pods created)
# => kubectl describe pod nginx-pod
# => kubectl describe pod nginx-pod2
# => kubectl describe pod nginx-pod3
# => kubectl describe pod nginx-pod4


# => kubectl get pods(get all the pod status)
# verify one by one
# => kubectl get pod nginx-pod

# get all the pods labels 
# => kubectl get pods --show-labels

# get the pods with specific labels with -l flag 
# => kubectl get pods -l dept=dev
# => kubectl get pods -l dept=test
# => kubectl get pods -l dept=dev,team=development-1
# => kubectl get pods -l dept=dev,team=development-2
# => kubectl get pods -l dept!=dev,team!=testing-1
      