apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
 containers: 
 - name: nginx
   image: nginx    
   ports:
   - name: my-web-port
     containerPort: 80 # Port number on the container 
     protocol: TCP # Protocol for the port

# by default its TCP  if not specified.

# containerPort: 80 means that the application inside the container is listening on port 80.
# This is the port that the containerized application will use to communicate with other services or containers.
# It simply informs Kubernetes that the container is expecting traffic on port 80.

#commands 

# kubectl create -f part02-pods/04-pod-ports.yaml
# kubectl get pods
# kubectl describe pod my-pod

# kubectl port-forward my-pod 8080:80
# http://localhost:8080 check
    
