apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never
  containers:
  - name: entrypointentrypoint
    image: vinsdocker/k8s-entrypoint
    command:  # to override the entrypoint on the docker image
     - "date"
      

# I have used the image vinsdocker/k8s-entrypoint which has an entrypoint echo "Hello World"
# Now I ahve used command to override the entrypoint
# which will print the date => Fri Apr  4 16:14:57 UTC 2025

 # Note : 
 # Command is like Entrypoint 
 # Args is like CMD
 # command → Overrides the Docker ENTRYPOINT
 # args → Overrides the Docker CMD

 # Entrypoint in Docker => Command in Kubernetes
 # CMD in Docker => Args in Kubernetes      

 # Remember 
 # Entrypoint in Docker is the command that runs when the container starts.
 # CMD in Docker is the default arguments to the entrypoint command.


# lets say is test-pod.yaml

# apiVersion: v1
# kind: Pod
# metadata:
#   name: test-pod
# spec:
#   containers:
#     - name: ubuntu
#       image: ubuntu
#       command: ["/bin/bash", "-c"]   # This is fixed
#       args: ["echo Hello && sleep 3600"]  # This can be changed

# => kubectl apply -f test-pod.yaml will run:
# /bin/bash -c "echo Hello && sleep 3600"