apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
 restartPolicy: Never
 terminationGracePeriodSeconds: 0
 containers:
   - name: ubuntu
     image: ubuntu
     env:
       - name: spring.profiles.active
         value: dev
       - name: spring.datasource.url
         value: jdbc:mysql://localhost:3306/myDB
       - name: spring.datasource.username
         value: springuser
       - name: spring.datasource.password
         value: springpassword
       - name: spring.jpa.hibernate.ddl-auto
         value: update  

     args:
        - "env"    # will print the env variables which we have set

        

# kubectl create -f 10-pod-evn.yaml
# kubectl get pods
# kubectl logs my-pod

# prints the env variables
# PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
# HOSTNAME=my-pod
# spring.datasource.username=springuser
# spring.datasource.password=springpassword
# spring.jpa.hibernate.ddl-auto=update
# spring.profiles.active=dev
# spring.datasource.url=jdbc:mysql://localhost:3306/myDB
# KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
# KUBERNETES_SERVICE_HOST=10.96.0.1
# KUBERNETES_SERVICE_PORT=443
# KUBERNETES_SERVICE_PORT_HTTPS=443
# KUBERNETES_PORT=tcp://10.96.0.1:443
# KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
# KUBERNETES_PORT_443_TCP_PROTO=tcp
# KUBERNETES_PORT_443_TCP_PORT=443
# HOME=/root

# kubectl delete pod my-pod

    