apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-ss
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 3
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx
        image: nginx
        
# StatefulSets do not support kubectl rollout or kubectl rollout undo like Deployments do
# Will br created one by one not at a time all will be created like in case of deployment       
# pod/my-ss-0   1/1     Running   0          159m
# pod/my-ss-1   1/1     Running   0          159m
# pod/my-ss-2   1/1     Running   0          159m

# Deployment: Same PVC (shared storage) or no storage → good for stateless apps.
# StatefulSet: Unique PVC → good for stateful apps like databases.

# StatefulSet:
#   pod-0 -> volume-0
#   pod-1 -> volume-1
#   pod-2 -> volume-2        


# kubectl delete pod my-ss-1 
# same pod will be again created automatically with same name