apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-ss
spec:
  serviceName: nginx # match the service name
  selector:
    matchLabels:
      app: my-app
  replicas: 3
  template:
    metadata:
      labels:
        app: my-app
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: nginx
        image: vinsdocker/nginx-gke
        # command: ["/bin/sh"]
        # args:
        #   - "-c"
        #   - |
        #     echo "<h1>Pod Name: $HOSTNAME</h1><h2>Hostname: $HOSTNAME</h2>" > /usr/share/nginx/html/index.html && \
        #     nginx -g 'daemon off;'
        # ports:
        #    - name: my-sts-port
        #      containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx # service name should be matched serviceName: nginx
spec:
  type: ClusterIP
  clusterIP: None #headless service
  selector:
    app: my-app
  ports:
  - port: 80
    targetPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  terminationGracePeriodSeconds: 1
  containers:
  - name: demo
    image: vinsdocker/util
    args:
    - "sleep"
    - "3600" 

# earlier problem was 
# while doung curl demo-pod it was taking to random pord
# => kubectl apply -f 03-sts-headless-svc.yaml
# => kubectl exec -it demo-pod -- bash
# => curl my-service (gives sometimes my-ss-0 or my-ss-1 or my-ss-2 )

# making to headless we have the option to request to specifc pord

# <pod-name>.<service-name>.<namespace>.svc.cluster.local 
# <statefulset-pod-name>.<headless-service-name> this will work smaller verion :)
# => kubectl exec -it demo-pod -- bash
# => nslookup nginx
# root@demo-pod:/# nslookup nginx
# Server:         10.96.0.10
# Address:        10.96.0.10#53

# Name:   nginx.default.svc.cluster.local
# Address: 10.244.1.25
# Name:   nginx.default.svc.cluster.local
# Address: 10.244.1.22
# Name:   nginx.default.svc.cluster.local
# Address: 10.244.1.23
# curl my-ss-0.nginx 
# curl my-ss-1.nginx 
# curl my-ss-2.nginx 


